name: Merge Dependabot PRs

on:
  schedule:
    - cron: '0 0 * * 0' # Runs weekly on Sunday at midnight
  workflow_dispatch:

jobs:
  merge-dependabot-prs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Fetch all branches
      run: git fetch --all

    - name: Merge dependabot branches
      run: |
        for branch in $(git branch -r | grep dependabot); do
          git checkout $branch
          git merge main --allow-unrelated-histories
          git checkout main
          git merge $branch --allow-unrelated-histories
        done

    - name: Create new PR
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'Merge dependabot PRs'
        branch: merge-dependabot-prs
        title: 'Merge dependabot PRs'
        body: 'This PR merges all open dependabot PRs into a single PR.'
